export const standalone = [
  {
    id: "utils",
    official: "utils/utils.ts",
    title: "utils.ts without getNextId/globalState",
    lilEntry: "src/layers/utils.lil",
    kind: "standalone",
    exports: null,
  },
  {
    id: "errors",
    official: "errors.ts",
    title: "prod die()",
    lilEntry: "src/layers/errors.lil",
    kind: "standalone",
    exports: ["die"],
  },
  {
    id: "iterable",
    official: "utils/iterable.ts",
    title: "makeIterable",
    lilEntry: "src/layers/iterable.lil",
    kind: "standalone",
    exports: ["makeIterable"],
  },
  {
    id: "comparer-leaf",
    official: "utils/comparer.ts",
    title: "compareIdentity + compareDefault",
    lilEntry: "src/layers/comparer-leaf.lil",
    kind: "standalone",
    exports: ["compareIdentity", "compareDefault"],
  },
];

export const slices = [
  {
    id: "host",
    official: null,
    title: "entire host.lil (tree-shake probe of JS interop)",
    lilEntry: "src/layers/slice-host.lil",
    kind: "slice",
    from: "host",
    exports: [
      "isFn",
      "isStr",
      "isObj",
      "isArr",
      "len",
      "toStr",
      "defineProperty",
      "assign",
      "makeIterable",
      "createInstanceofPredicate",
    ],
  },
  {
    id: "comparer",
    official: "utils/comparer.ts",
    title: "comparer via kernel/types",
    lilEntry: "src/layers/slice-comparer.lil",
    kind: "slice",
    from: "mixed",
    exports: ["compareIdentity", "compareDefault", "compareStructural", "compareShallow"],
  },
  {
    id: "atom",
    official: "core/atom.ts",
    title: "Atom + createAtom from kernel",
    lilEntry: "src/layers/slice-atom.lil",
    kind: "slice",
    from: "kernel",
    exports: ["Atom", "createAtom", "$mobx"],
  },
  {
    id: "globalstate",
    official: "core/globalstate.ts",
    title: "globalState + isolate/reset",
    lilEntry: "src/layers/slice-globalstate.lil",
    kind: "slice",
    from: "kernel",
    exports: ["globalState", "getGlobalState", "resetGlobalState", "isolateGlobalState", "getNextId"],
  },
  {
    id: "derivation",
    official: "core/derivation.ts",
    title: "track/shouldCompute/untracked",
    lilEntry: "src/layers/slice-derivation.lil",
    kind: "slice",
    from: "kernel",
    exports: [
      "shouldCompute",
      "trackDerivedFunction",
      "clearObserving",
      "untracked",
      "untrackedStart",
      "untrackedEnd",
      "CaughtException",
      "isCaughtException",
    ],
  },
  {
    id: "observable-core",
    official: "core/observable.ts",
    title: "reportObserved / reportChanged / observers",
    lilEntry: "src/layers/slice-observable-core.lil",
    kind: "slice",
    from: "kernel",
    exports: [
      "reportObserved",
      "reportChanged",
      "addObserver",
      "removeObserver",
      "startBatch",
      "endBatch",
      "propagateChanged",
    ],
  },
  {
    id: "action",
    official: "core/action.ts",
    title: "createAction / executeAction",
    lilEntry: "src/layers/slice-action.lil",
    kind: "slice",
    from: "kernel",
    exports: ["createAction", "executeAction", "_startAction", "_endAction"],
  },
  {
    id: "spy",
    official: "core/spy.ts",
    title: "spy (prod no-op)",
    lilEntry: "src/layers/slice-spy.lil",
    kind: "slice",
    from: "kernel",
    exports: ["isSpyEnabled", "spyReport", "spyReportStart", "spyReportEnd", "spy"],
  },
  {
    id: "reaction",
    official: "core/reaction.ts",
    title: "Reaction",
    lilEntry: "src/layers/slice-reaction.lil",
    kind: "slice",
    from: "kernel",
    exports: ["Reaction", "runReactions", "onReactionError"],
  },
  {
    id: "computed-value",
    official: "core/computedvalue.ts",
    title: "ComputedValue",
    lilEntry: "src/layers/slice-computed-value.lil",
    kind: "slice",
    from: "kernel",
    exports: ["ComputedValue", "isComputedValue"],
  },
  {
    id: "listen-utils",
    official: "types/listen-utils.ts",
    title: "has/register/notify listeners",
    lilEntry: "src/layers/slice-listen-utils.lil",
    kind: "slice",
    from: "kernel",
    exports: ["hasListeners", "registerListener", "notifyListeners"],
  },
  {
    id: "intercept-utils",
    official: "types/intercept-utils.ts",
    title: "interceptors",
    lilEntry: "src/layers/slice-intercept-utils.lil",
    kind: "slice",
    from: "kernel",
    exports: ["hasInterceptors", "registerInterceptor", "interceptChange"],
  },
  {
    id: "transaction",
    official: "api/transaction.ts",
    title: "transaction",
    lilEntry: "src/layers/slice-transaction.lil",
    kind: "slice",
    from: "kernel",
    exports: ["transaction"],
  },
  {
    id: "observable-value",
    official: "types/observablevalue.ts",
    title: "ObservableValue",
    lilEntry: "src/layers/slice-observable-value.lil",
    kind: "slice",
    from: "types",
    exports: ["ObservableValue", "isBoxedObservable"],
  },
  {
    id: "observable-object",
    official: "types/observableobject.ts",
    title: "ObservableObjectAdministration",
    lilEntry: "src/layers/slice-observable-object.lil",
    kind: "slice",
    from: "types",
    exports: ["ObservableObjectAdministration", "asObservableObject"],
  },
  {
    id: "observable-array",
    official: "types/observablearray.ts",
    title: "ObservableArray",
    lilEntry: "src/layers/slice-observable-array.lil",
    kind: "slice",
    from: "types",
    exports: ["createObservableArray"],
  },
  {
    id: "observable-map",
    official: "types/observablemap.ts",
    title: "ObservableMap",
    lilEntry: "src/layers/slice-observable-map.lil",
    kind: "slice",
    from: "types",
    exports: ["ObservableMap"],
  },
  {
    id: "observable-set",
    official: "types/observableset.ts",
    title: "ObservableSet",
    lilEntry: "src/layers/slice-observable-set.lil",
    kind: "slice",
    from: "types",
    exports: ["ObservableSet"],
  },
  {
    id: "eq",
    official: "utils/eq.ts",
    title: "deepEqual",
    lilEntry: "src/layers/slice-eq.lil",
    kind: "slice",
    from: "types",
    exports: ["deepEqual"],
  },
  {
    id: "autorun",
    official: "api/autorun.ts",
    title: "autorun + reaction + when",
    lilEntry: "src/layers/slice-autorun.lil",
    kind: "slice",
    from: "types",
    exports: ["autorun", "reaction", "when"],
  },
  {
    id: "observable-api",
    official: "api/observable.ts",
    title: "observable / computed / action / flow",
    lilEntry: "src/layers/slice-observable-api.lil",
    kind: "slice",
    from: "types",
    exports: ["observable", "computed", "action", "flow", "extendObservable"],
  },
  {
    id: "object-api",
    official: "api/object-api.ts",
    title: "keys/values/get/set/has/remove",
    lilEntry: "src/layers/slice-object-api.lil",
    kind: "slice",
    from: "types",
    exports: ["keys", "values", "entries", "get", "set", "has", "remove"],
  },
  {
    id: "isobservable",
    official: "api/isobservable.ts",
    title: "isObservable / isObservableProp",
    lilEntry: "src/layers/slice-isobservable.lil",
    kind: "slice",
    from: "types",
    exports: ["isObservable", "isObservableProp"],
  },
  {
    id: "iscomputed",
    official: "api/iscomputed.ts",
    title: "isComputed / isComputedProp",
    lilEntry: "src/layers/slice-iscomputed.lil",
    kind: "slice",
    from: "types",
    exports: ["isComputed", "isComputedProp"],
  },
  {
    id: "tojs",
    official: "api/tojs.ts",
    title: "toJS",
    lilEntry: "src/layers/slice-tojs.lil",
    kind: "slice",
    from: "types",
    exports: ["toJS"],
  },
  {
    id: "makeobservable",
    official: "api/makeObservable.ts",
    title: "makeObservable / makeAutoObservable",
    lilEntry: "src/layers/slice-makeobservable.lil",
    kind: "slice",
    from: "types",
    exports: ["makeObservable", "makeAutoObservable"],
  },
  {
    id: "observe",
    official: "api/observe.ts",
    title: "observe / intercept",
    lilEntry: "src/layers/slice-observe.lil",
    kind: "slice",
    from: "types",
    exports: ["observe", "intercept"],
  },
  {
    id: "flow",
    official: "api/flow.ts",
    title: "flow + FlowCancellationError",
    lilEntry: "src/layers/slice-flow.lil",
    kind: "slice",
    from: "types",
    exports: ["flow", "flowBound", "FlowCancellationError", "isFlowCancellationError", "flowResult"],
  },
  {
    id: "when",
    official: "api/when.ts",
    title: "when",
    lilEntry: "src/layers/slice-when.lil",
    kind: "slice",
    from: "types",
    exports: ["when"],
  },
  {
    id: "action-api",
    official: "api/action.ts",
    title: "action / runInAction / isAction",
    lilEntry: "src/layers/slice-action-api.lil",
    kind: "slice",
    from: "mixed",
    exports: ["action", "autoAction", "actionBound", "autoActionBound", "runInAction", "isAction"],
  },
  {
    id: "computed-api",
    official: "api/computed.ts",
    title: "computed / computedStruct",
    lilEntry: "src/layers/slice-computed-api.lil",
    kind: "slice",
    from: "types",
    exports: ["computed", "computedStruct"],
  },
  {
    id: "configure",
    official: "api/configure.ts",
    title: "configure",
    lilEntry: "src/layers/slice-configure.lil",
    kind: "slice",
    from: "types",
    exports: ["configure"],
  },
  {
    id: "extendobservable",
    official: "api/extendobservable.ts",
    title: "extendObservable",
    lilEntry: "src/layers/slice-extendobservable.lil",
    kind: "slice",
    from: "types",
    exports: ["extendObservable"],
  },
  {
    id: "extras",
    official: "api/extras.ts",
    title: "getDependencyTree / getObserverTree",
    lilEntry: "src/layers/slice-extras.lil",
    kind: "slice",
    from: "types",
    exports: ["getDependencyTree", "getObserverTree"],
  },
  {
    id: "become-observed",
    official: "api/become-observed.ts",
    title: "onBecomeObserved / onBecomeUnobserved",
    lilEntry: "src/layers/slice-become-observed.lil",
    kind: "slice",
    from: "types",
    exports: ["onBecomeObserved", "onBecomeUnobserved"],
  },
  {
    id: "intercept",
    official: "api/intercept.ts",
    title: "intercept",
    lilEntry: "src/layers/slice-intercept.lil",
    kind: "slice",
    from: "types",
    exports: ["intercept"],
  },
  {
    id: "intercept-read",
    official: "api/intercept-read.ts",
    title: "interceptReads",
    lilEntry: "src/layers/slice-intercept-read.lil",
    kind: "slice",
    from: "types",
    exports: ["interceptReads"],
  },
  {
    id: "type-utils",
    official: "types/type-utils.ts",
    title: "getAtom / getAdministration / getDebugName",
    lilEntry: "src/layers/slice-type-utils.lil",
    kind: "slice",
    from: "types",
    exports: ["getAtom", "getAdministration", "getDebugName"],
  },
  {
    id: "dynamicobject",
    official: "types/dynamicobject.ts",
    title: "asDynamicObservableObject",
    lilEntry: "src/layers/slice-dynamicobject.lil",
    kind: "slice",
    from: "types",
    exports: ["asDynamicObservableObject"],
  },
  {
    id: "overrideannotation",
    official: "types/overrideannotation.ts",
    title: "override / isOverride",
    lilEntry: "src/layers/slice-overrideannotation.lil",
    kind: "slice",
    from: "types",
    exports: ["override", "isOverride"],
  },
  {
    id: "observableannotation",
    official: "types/observableannotation.ts",
    title: "createObservableAnnotation",
    lilEntry: "src/layers/slice-observableannotation.lil",
    kind: "slice",
    from: "types",
    exports: ["createObservableAnnotation"],
  },
  {
    id: "computedannotation",
    official: "types/computedannotation.ts",
    title: "createComputedAnnotation",
    lilEntry: "src/layers/slice-computedannotation.lil",
    kind: "slice",
    from: "types",
    exports: ["createComputedAnnotation"],
  },
  {
    id: "actionannotation",
    official: "types/actionannotation.ts",
    title: "createActionAnnotation",
    lilEntry: "src/layers/slice-actionannotation.lil",
    kind: "slice",
    from: "types",
    exports: ["createActionAnnotation"],
  },
  {
    id: "autoannotation",
    official: "types/autoannotation.ts",
    title: "createAutoAnnotation / autoAnnotation",
    lilEntry: "src/layers/slice-autoannotation.lil",
    kind: "slice",
    from: "types",
    exports: ["createAutoAnnotation", "autoAnnotation"],
  },
  {
    id: "decorators",
    official: "api/decorators.ts",
    title: "assert20223DecoratorType",
    lilEntry: "src/layers/slice-decorators.lil",
    kind: "slice",
    from: "kernel",
    exports: ["assert20223DecoratorType"],
  },
  {
    id: "decoratorannotation",
    official: "api/decoratorannotation.ts",
    title: "createDecoratorAnnotation",
    lilEntry: "src/layers/slice-decoratorannotation.lil",
    kind: "slice",
    from: "kernel",
    exports: ["createDecoratorAnnotation"],
  },
  {
    id: "annotation",
    official: "api/annotation.ts",
    title: "isAnnotation",
    lilEntry: "src/layers/slice-annotation.lil",
    kind: "slice",
    from: "kernel",
    exports: ["isAnnotation"],
  },
  {
    id: "isaction",
    official: "api/action.ts",
    title: "isAction from kernel (leaf of action.ts)",
    lilEntry: "src/layers/slice-isaction.lil",
    kind: "slice",
    from: "kernel",
    exports: ["isAction"],
  },
  {
    id: "init-observable",
    official: "types/type-utils.ts",
    title: "initObservable from kernel",
    lilEntry: "src/layers/slice-init-observable.lil",
    kind: "slice",
    from: "kernel",
    exports: ["initObservable"],
  },
  {
    id: "full",
    official: "mobx.ts",
    title: "full public entry",
    lilEntry: "src/mobx.lil",
    kind: "full",
    from: "entry",
    exports: [],
  },
];

export const allLayers = [...standalone, ...slices];
